import type { CommerceJobStage, CommerceJobStatus } from "./generation-api";
export const stageMessages: Record<CommerceJobStage, string> = { UNDERSTANDING_PRODUCT: "Entendendo o produto...", MAPPING_COMMERCIAL_OPPORTUNITIES: "Mapeando oportunidades comerciais...", BUILDING_STRATEGY: "Definindo a melhor estratégia para este produto...", BUILDING_CONTENT_PLAN: "Organizando as oportunidades de conteúdo...", GENERATING_BRIEFS: "Preparando os Briefings do Conteúdo...", FINALIZING: "Finalizando..." };
export const statusLabels: Record<CommerceJobStatus, string> = { QUEUED: "Na fila", RUNNING: "Analisando", SUCCEEDED: "Pronto", FAILED: "Falhou", CANCELLED: "Cancelada" };
export function stageMessage(stage: CommerceJobStage | null) { return stage ? stageMessages[stage] : "Preparando a análise..."; }
export function statusMessage(status: CommerceJobStatus, productName?: string) { if (status === "QUEUED") return `${productName ? `${productName} foi confirmado. ` : ""}A análise começará em breve.`; if (status === "RUNNING") return "A análise continua em segundo plano. Você pode continuar usando a aplicação."; if (status === "SUCCEEDED") return "Seu produto está pronto para revisão."; if (status === "CANCELLED") return "A análise foi cancelada. Você pode tentar novamente."; return "Não foi possível concluir a análise. Seus fatos foram preservados e você pode tentar novamente."; }
export const generationStatusLabel = (status: CommerceJobStatus | string) => statusLabels[status as CommerceJobStatus] ?? "Estado desconhecido";
export const generationStatusMessage = (status: CommerceJobStatus | string, _count?: number) => { const normalized: Record<string, CommerceJobStatus> = { queued: "QUEUED", running: "RUNNING", succeeded: "SUCCEEDED", failed: "FAILED", cancelled: "CANCELLED" }; return statusMessage(normalized[status] ?? status as CommerceJobStatus); };
export const isActiveGeneration = (status?: CommerceJobStatus | string | null) => status === "QUEUED" || status === "RUNNING" || status === "queued" || status === "running";
export const isRetryableGeneration = (status?: CommerceJobStatus | string | null) => status === "FAILED" || status === "CANCELLED" || status === "failed" || status === "cancelled";
export const isLimitError = (code?: string | null) => code === "GEN-ACTIVE" || code === "generation_capacity";
export const isCapacityUnavailableError = (code?: string | null) => code === "GEN-CAPACITY" || code === "capacity_unavailable";
export function contentDimensionLabels(strategy: unknown, content: Record<string, unknown>) { const dimensions = ((strategy as Record<string, unknown> | null)?.dimensions as Record<string, unknown> | undefined) ?? {}; const label = (key: string) => { const id = content[key]; const values = dimensions[key.replace(/_id$/, "s")]; const list = Array.isArray(values) ? values as Array<Record<string, unknown>> : []; return String(list.find((item) => item.id === id)?.label ?? id ?? "Não informado"); }; return { audience: label("audience_id"), pain: label("pain_id"), desire: label("desire_id"), benefit: label("benefit_id"), objection: label("objection_id"), angle: label("angle_id") }; }
