import { CommerceIntelligenceJobStatus } from "@prisma/client";
import { prisma } from "../db";
import { readCookie, sameOriginRequest, SESSION_COOKIE, json } from "../identity/http";
import { resolveSession } from "../identity/service";
import { isValidIdempotencyKey } from "../products/service";
import { GenerationError, publicGenerationError } from "./errors";
import { startCommerceIntelligence, findBlockingGeneration, activeJobWhere } from "./service";
type GenerationEnvelopeJob = { id: string; productId: string; status: string; stage: string | null; targetContentCount: number; publicErrorMessage: string | null; createdAt: Date; startedAt: Date | null; finishedAt: Date | null; attempt: number; strategies?: Array<{ payload: unknown }>; plan?: { payload: unknown } | null; contents?: Array<{ id: string; productId: string; planId: string; opportunityId: string | null; position: number; status: string; briefs?: Array<{ payload: unknown }> }> };
function payloadObject(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
export function projectBriefPayload(value: unknown): Record<string, unknown> { const payload = payloadObject(value); const result = Object.fromEntries(Object.entries(payload).filter(([key]) => key !== "scenes")); const development = Array.isArray(payload.development) ? payload.development.filter((point): point is string => typeof point === "string") : []; return { ...result, development }; }
async function session(req: Request) { const token = readCookie(req, SESSION_COOKIE); return token ? resolveSession(token) : null; }
const include = { strategies: true, plan: true, contents: { include: { briefs: { orderBy: { version: "asc" as const }, take: 1 } } } };
function noStore(response: Response) { response.headers.set("cache-control", "no-store, max-age=0"); return response; }
export function currentGenerationFilter(tenantId: string, userId: string, productId?: string) {
  return { tenantId, userId, ...(productId ? { productId } : {}), status: { in: [CommerceIntelligenceJobStatus.QUEUED, CommerceIntelligenceJobStatus.RUNNING, CommerceIntelligenceJobStatus.SUCCEEDED, CommerceIntelligenceJobStatus.FAILED, CommerceIntelligenceJobStatus.CANCELLED] as CommerceIntelligenceJobStatus[] } };
}
async function envelope(job: GenerationEnvelopeJob) { const publish = job.status === "SUCCEEDED"; const contents = publish ? (job.contents ?? []).map((content) => ({ id: content.id, productId: content.productId, planId: content.planId, opportunityId: content.opportunityId, position: content.position, status: content.status, ...projectBriefPayload(content.briefs?.[0]?.payload) })) : []; return { id: job.id, productId: job.productId, status: job.status, stage: job.stage, targetContentCount: job.targetContentCount, error: job.publicErrorMessage, createdAt: job.createdAt.toISOString(), startedAt: job.startedAt?.toISOString() ?? null, finishedAt: job.finishedAt?.toISOString() ?? null, attempt: job.attempt, readiness: publish ? "READY" : job.status === "FAILED" || job.status === "CANCELLED" ? "FAILED" : "ANALYZING", strategy: publish ? payloadObject(job.strategies?.[0]?.payload) : {}, plan: publish ? payloadObject(job.plan?.payload) : {}, contents }; }
export async function handleCurrent(req: Request) { const s = await session(req); if (!s) return json(401, { error: "Sessão inválida", code: "UNAUTHENTICATED" }); const productId = new URL(req.url).searchParams.get("productId"); if (productId !== null && !/^[A-Za-z0-9_-]{1,100}$/.test(productId)) return json(400, { error: "Product inválido", code: "GEN-PRODUCT" }); const active = await findBlockingGeneration(s.tenantId, s.userId, productId ?? undefined); console.info("[generation-current]", { tenantId: s.tenantId, userId: s.userId, productId: productId ?? null, activeJobId: active?.id ?? null, activeStatus: active?.status ?? null }); if (active) return noStore(Response.json(await envelope(active))); const where = currentGenerationFilter(s.tenantId, s.userId, productId ?? undefined); const job = await prisma.commerceIntelligenceJob.findFirst({ where: { ...where, status: { in: [CommerceIntelligenceJobStatus.SUCCEEDED, CommerceIntelligenceJobStatus.FAILED, CommerceIntelligenceJobStatus.CANCELLED] } }, include, orderBy: { createdAt: "desc" } }); return noStore(Response.json(job ? await envelope(job) : null)); }
export async function handleGet(req: Request, id: string) { const s = await session(req); if (!s) return json(401, { error: "Sessão inválida", code: "UNAUTHENTICATED" }); const job = await prisma.commerceIntelligenceJob.findFirst({ where: { id, tenantId: s.tenantId }, include }); return job ? noStore(Response.json(await envelope(job))) : json(404, { error: "Não encontrado", code: "NOT_FOUND" }); }
export async function handleRetry(req: Request, id: string) { if (!sameOriginRequest(req)) return json(403, { error: "Origem não autorizada", code: "ORIGIN_FORBIDDEN" }); const s = await session(req); const key = req.headers.get("Idempotency-Key"); if (!s || !isValidIdempotencyKey(key)) return json(400, { error: "Requisição inválida", code: "GEN-IDEMPOTENCY" }); const old = await prisma.commerceIntelligenceJob.findFirst({ where: { id, tenantId: s.tenantId, userId: s.userId, status: { in: ["FAILED", "CANCELLED"] } } }); if (!old) return json(404, { error: "Não encontrado", code: "NOT_FOUND" }); try { const job = await startCommerceIntelligence({ tenantId: s.tenantId, userId: s.userId, productId: old.productId, idempotencyKey: key }); return noStore(Response.json(await envelope(job), { status: 202 })); } catch (error) { const code = error instanceof GenerationError ? error.code : "GEN-PROVIDER"; const status = code === "GEN-ACTIVE" || code === "GEN-READY" || code === "GEN-PRODUCT-CAPACITY" ? 409 : code === "GEN-CAPACITY" ? 429 : 400; return json(status, { error: publicGenerationError(code), code }); } }
export async function handleCancel(req: Request, id: string) { if (!sameOriginRequest(req)) return json(403, { error: "Origem não autorizada", code: "ORIGIN_FORBIDDEN" }); const s = await session(req); if (!s) return json(401, { error: "Sessão inválida", code: "UNAUTHENTICATED" }); const current = await prisma.commerceIntelligenceJob.findFirst({ where: { id, tenantId: s.tenantId, userId: s.userId } }); if (!current || current.status !== "QUEUED") return json(409, { error: "O cancelamento não está disponível durante a execução.", code: "GEN-CANCEL-UNSAFE" }); const result = await prisma.$transaction(async (tx) => { const changed = await tx.commerceIntelligenceJob.updateMany({ where: { id, tenantId: s.tenantId, userId: s.userId, status: "QUEUED" }, data: { status: "CANCELLED", finishedAt: new Date(), leaseOwnerId: null, leaseDeadlineAt: null } }); if (changed.count) await tx.generationUsageReservation.updateMany({ where: { tenantId: s.tenantId, jobId: id, status: "RESERVED" }, data: { status: "RELEASED", reason: "CANCELLED" } }); return changed.count; }); return result ? noStore(Response.json({ id, productId: current.productId, status: "CANCELLED", stage: current.stage, targetContentCount: current.targetContentCount, error: null, createdAt: current.createdAt.toISOString(), startedAt: current.startedAt?.toISOString() ?? null, finishedAt: new Date().toISOString(), attempt: current.attempt, readiness: "FAILED", strategy: null, plan: null, contents: [] })) : json(404, { error: "Não encontrado", code: "NOT_FOUND" }); }
